/* Build the shipped, solver-graded deal pool -> deals.js
 * Scans reproducible Microsoft deal numbers from 1 upward, grades each once,
 * and fills all five tier buckets. Every deal is proven solvable; Fort Knox
 * deals are additionally verified solvable with only 3 free cells.
 * Usage: node tools/build-pool.js [perTier] [maxScan]
 */
const fs = require('fs');
const path = require('path');
const G = require('../game.js');
const S = require('../solver.js');

const PER_TIER = parseInt(process.argv[2] || '100', 10);
const MAX_SCAN = parseInt(process.argv[3] || '6000', 10);

const pool = { 1: [], 2: [], 3: [], 4: [], 5: [] };
const full = () => [1, 2, 3, 4, 5].every((t) => pool[t].length >= PER_TIER);

const t0 = Date.now();
let scanned = 0, solvable = 0, skippedCap = 0, fkRejected = 0;

for (let dn = 1; dn <= MAX_SCAN && !full(); dn++) {
  scanned++;
  const g = S.gradeDeal(dn);
  if (!g.solvable) { skippedCap++; continue; }
  solvable++;
  const t = g.tier;
  if (pool[t].length >= PER_TIER) continue;
  if (t === 5) {
    const r3 = S.solve(G.newState(dn, 3), { maxNodes: 250000, weight: 3, wantPath: false });
    if (!r3.solvable) { fkRejected++; continue; }
  }
  pool[t].push(dn);
  if (scanned % 100 === 0) {
    process.stdout.write(`  scanned ${scanned}  buckets [${[1,2,3,4,5].map((x)=>pool[x].length).join(',')}]  ${((Date.now()-t0)/1000).toFixed(0)}s\n`);
  }
}

console.log(`\nDone. scanned=${scanned} solvable=${solvable} skippedCap=${skippedCap} fkRejected=${fkRejected} in ${((Date.now()-t0)/1000).toFixed(0)}s`);
console.log('bucket sizes:', [1,2,3,4,5].map((t)=>pool[t].length));

const header = `/* deals.js — solver-graded FreeCell deal pool for "The Vault".
 * AUTO-GENERATED by tools/build-pool.js — do not hand-edit.
 * Each array holds Microsoft FreeCell deal numbers whose solver-graded
 * difficulty falls in that tier's band. Every deal was verified solvable
 * (Fort Knox also with only 3 free cells). ${PER_TIER}/tier, scanned ${scanned} deals.
 */
const DEAL_POOL = ${JSON.stringify(pool, null, 0)};
if (typeof module !== 'undefined' && module.exports) module.exports = { DEAL_POOL };
`;
fs.writeFileSync(path.join(__dirname, '..', 'deals.js'), header);
console.log('wrote deals.js');
